# Railway deployment configuration
[build]
builder = "maven"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/uw-workbench-backend-*.jar --server.port=$PORT"
restartPolicyType = "always"

[env]
# Java optimization for Railway
JAVA_TOOL_OPTIONS = "-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC"

# Spring Boot configuration
SPRING_PROFILES_ACTIVE = "production"